version: 1
default_environment: dev
project_id: b77cad0a-ffd8-494e-9e6b-18d6eacb71d4
plugins:
  extractors:
  - name: tap-pocket
    namespace: tap_pocket
    pip_url: git+https://github.com/edgarrmondragon/tap-pocket.git
    executable: tap-pocket
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: consumer_key
      kind: password
    - name: access_token
      kind: password
    - name: start_date
      kind: integer
  loaders:
  - name: target-sqlite
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-sqlite.git@json-dump-objects-and-arrays
    config:
      database: output/${MELTANO_EXTRACT__LOAD_SCHEMA}.db
environments:
- name: dev
  config:
    plugins:
      loaders:
      - name: target-sqlite
        config:
          batch_size: 15
- name: staging
- name: prod
  config:
    plugins:
      loaders:
      - name: target-sqlite
        config:
          batch_size: 500
