version: 1
default_environment: dev
project_id: b77cad0a-ffd8-494e-9e6b-18d6eacb71d4
plugins:
  extractors:
  - name: tap-pocket
    namespace: tap_pocket
    pip_url: git+https://github.com/edgarrmondragon/tap-pocket.git
    executable: tap-pocket
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: consumer_key
      kind: password
    - name: access_token
      kind: password
    - name: start_date
      kind: integer
  loaders:
  - name: target-sqlite
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-sqlite.git@json-dump-objects-and-arrays
    config:
      database: output/${MELTANO_ENVIRONMENT}/${MELTANO_EXTRACT__LOAD_SCHEMA}.db
    dialect: sqlite
  transformers:
  - name: dbt-sqlite
    namespace: sqlite
    pip_url: dbt-core~=1.1.0 dbt-sqlite~=1.0.0
    executable: dbt
    settings:
    - name: project_dir
      value: $MELTANO_PROJECT_ROOT/transform
    - name: profiles_dir
      env_aliases:
      - DBT_PROFILES_DIR
      value: $MELTANO_PROJECT_ROOT/transform/profile
    commands:
      run:
        args: run
        description: Compile SQL and execute against the current target database.
      docs-serve: docs serve
      docs-generate: docs generate
      clean:
        args: clean
        description: Delete all folders in the clean-targets list (usually the dbt_modules
          and target directories.)
      test: test
    config:
      target: sqlite
  utilities:
  - name: sqlfluff
    pip_url: sqlfluff>=0.13 sqlfluff-templater-dbt>=0.13 dbt-core~=1.1.0 dbt-sqlite~=1.0.0
    commands:
      lint:
        args: lint transform/models
        description: Lint SQL in transform models
      fix:
        args: fix transform/models
        description: Fix SQL
environments:
- name: dev
  config:
    plugins:
      loaders:
      - name: target-sqlite
        config:
          batch_size: 15
- name: staging
- name: prod
  config:
    plugins:
      loaders:
      - name: target-sqlite
        config:
          batch_size: 500
