config:
  send_anonymous_usage_stats: false
  use_colors: true

self:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      threads: 4
      method: service-account
      project: "{{ env_var('DBT_BIGQUERY_PROJECT_ID') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET_ID') }}"
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE') }}"
      location: "{{ env_var('DBT_BIGQUERY_LOCATION') }}"
