name: "personal_data"
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: "self"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  personal_data:
    +materialized: table
    pocket:
      +enabled: true
      +tags: [pocket, reading]
