config:
  send_anonymous_usage_stats: false
  use_colors: true

self:
  target: "{{ env_var('MELTANO_ENVIRONMENT', 'dev') }}"
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: database
      schema: main
      schemas_and_paths:
        main: "{{ env_var('MELTANO_PROJECT_ROOT') }}/output/warehouse.db"
      schema_directory: "{{ env_var('PWD') }}/output"
