name: Meltano Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Meltano Environment
        required: true
        default: prod
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  meltano-run:
    name: Meltano Run Pipeline for ${{ matrix.source }}
    runs-on: ubuntu-latest
    container:
      image: meltano/meltano:v1.103.1-python3.9
      env:
        MELTANO_ENVIRONMENT: ${{ github.event.inputs.environment || 'prod' }}
        MELTANO_CLI_LOG_LEVEL: ${{ github.event.inputs.logLevel || 'warning' }}
        TAP_POCKET_CONSUMER_KEY: ${{ secrets.TAP_POCKET_CONSUMER_KEY }}
        TAP_POCKET_ACCESS_TOKEN: ${{ secrets.TAP_POCKET_ACCESS_TOKEN }}
    strategy:
      matrix:
        include:
          - { source: "Pocket", tap: "tap-pocket" }
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Check Meltano
        run: |
          meltano --version

      - name: Install Plugins
        run: |
          meltano install

      - name: Run
        run: |
          meltano run ${{ matrix.tap }} target-sqlite

      - name: Upload ${{ matrix.source }} Data
        uses: actions/upload-artifact@v3.0.0
        with:
          name: raw-data
          path: output/*.db

  transform:
    name: Data Transformation with dbt-sqlite
    runs-on: ubuntu-latest
    needs: meltano-run
    container:
      image: meltano/meltano:v1.103.1-python3.9
      env:
        MELTANO_ENVIRONMENT: ${{ github.event.inputs.environment || 'prod' }}
        MELTANO_CLI_LOG_LEVEL: ${{ github.event.inputs.logLevel || 'warning' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Check Meltano
        run: |
          meltano --version

      - name: Install dbt-sqlite
        run: |
          meltano install

      - name: Download raw data
        uses: actions/download-artifact@v3.0.0
        with:
          name: raw-data
          path: output/

      - name: Transform
        run: |
          meltano run dbt-sqlite:run

      - name: Test Data
        run: |
          meltano test dbt-sqlite

      - name: Upload Data Warehouse
        uses: actions/upload-artifact@v3.0.0
        with:
          name: data-warehouse
          path: output/warehouse.db
