name: Meltano Pipeline

on:
  pull_request:
    paths:
      - tranform/models/**.sql
  push:
    branches: [main]
    paths:
      - tranform/models/**.sql
  workflow_dispatch:
    inputs:
      environment:
        description: Meltano Environment
        required: true
        default: prod
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  MELTANO_ENVIRONMENT: ${{ github.event.inputs.environment || 'prod' }}
  MELTANO_CLI_LOG_LEVEL: ${{ github.event.inputs.logLevel || 'warning' }}
  BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
  BQ_LOCATION: ${{ secrets.BQ_LOCATION }}

jobs:
  meltano-run:
    if: "github.event_name == 'workflow_dispatch'"
    name: Meltano Run Pipeline for ${{ matrix.source }}
    runs-on: ubuntu-latest
    container:
      image: meltano/meltano:v1.103.1-python3.9
      env:
        TAP_POCKET_CONSUMER_KEY: ${{ secrets.TAP_POCKET_CONSUMER_KEY }}
        TAP_POCKET_ACCESS_TOKEN: ${{ secrets.TAP_POCKET_ACCESS_TOKEN }}
    strategy:
      matrix:
        include:
          - { source: "Pocket", tap: "tap-pocket" }
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Setup Google Credentials
        env:
          CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo "${CREDENTIALS}" | base64 --decode > .secrets/credentials.json

      - name: Check Meltano
        run: |
          meltano --version

      - name: Install Plugins
        run: |
          meltano install

      - name: Run
        run: |
          meltano run ${{ matrix.tap }} target-bigquery

  transform:
    name: Data Transformation with dbt-bigquery
    runs-on: ubuntu-latest
    needs: meltano-run
    container:
      image: meltano/meltano:v1.103.1-python3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Setup Google Credentials
        env:
          CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo "${CREDENTIALS}" | base64 --decode > .secrets/credentials.json

      - name: Check Meltano
        run: |
          meltano --version

      - name: Install dbt-bigquery
        run: |
          meltano install transformer dbt-bigquery

      - name: Lint
        continue-on-error: true
        run: |
          meltano invoke dbt-bigquery:lint --format github-annotation-native

      - name: Transform
        run: |
          meltano run dbt-bigquery:run

      - name: Test Data
        run: |
          meltano test dbt-bigquery
